name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run MATLAB Tests
    strategy:
      matrix:
        release: [R2021a, R2021b, R2022a, R2022b, R2023a, R2023b, R2024a]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - if: ${{ matrix.os }} == 'ubuntu-latest'
        name: Start display server
        run: |
          sudo apt-get install xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.release }}
      - name: Run tests
        uses: matlab-actions/run-tests@v2
